
baseURL= "https://osacon.io"
canonifyURLs = false
title = "The Open Source Analytics Conference"
description = "The Open Source Analytics Conference (OSA CON) is the go-to conference for all things open-source analytics."
enableRobotsTXT = true
RemovePathAccents = true
DefaultContentLanguage = "en"

theme = "osacon"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"


############################## navigation ###############################
[menu]

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

  #[[menu.main]]
  #  identifier = "program"
  #  name = "Program"
  #  url = "/program"
  #  weight = 2

  #[[menu.main]]
  #  identifier = "schedule"
  #  name = "Schedule"
  #  url = "/program"
  #  parent = "program"
  #  weight = 1

  #[[menu.main]]
  #  name = "Sessions"
  #  url = "/sessions/2024"
  #  weight = 2
  #  parent = "program"

  #[[menu.main]]
  #  name = "Speakers"
  #  url = "speakers"
  #  weight = 3
  #  parent = "program"

  [[menu.main]]
  name = "Sessions"
  URL = "sessions/2024/"
  weight = 2

  [[menu.main]]
  name = "Speakers"
  URL = "speakers/archive/"
  weight = 2

  [[menu.main]]
    identifier = "sponsor"
    name = "Sponsors"
    url = "sponsors"
    weight = 2

  [[menu.main]]
    identifier = "sponsor0"
    name = "2024 Sponsors"
    url = "/sponsors"
    parent = "sponsor"
    weight = 1

  [[menu.main]]
    identifier = "sponsor1"
    name = "Prospectus"
    url = "/files/OSACon2024_Prospectus_v1_4.pdf"
    weight = 2
    parent = "sponsor"

  [[menu.main]]
  name = "Get Involved"
  URL = "get-involved"
  weight = 6

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 7


# Everything below this are Site Params

[params]
description = "The Open Source Analytics Conference (OSA CON) is the go-to conference for all things open-source analytics."
logo = "/images/osacon2025-logo-h.png"
home = "Home"
privacy_policy = "/privacy"
google_analytics = "G-GLFP2KJWR4"
live_link = "https://us.airmeet.com/e/69f1f9b0-2f11-11ef-82f4-1d5f1667121e"

# First one is picked as the Twitter card image if not set on page.
images = ["/images/osacon2024-card.jpg"]
start_date = "2023-12-12T09:00-05:00"
end_date = "2023-12-14T17:00-05:00" 

[params.hero]
text = "November 04-05, 2025. Free, online."

[params.hero.cta1]
text = "Become a speaker"
link = "http://sessionize.com/osa-con-2024"

# Navigation button
[params.navigation_button]
enable = false
label = "Join event"
link = "https://us.airmeet.com/e/69f1f9b0-2f11-11ef-82f4-1d5f1667121e"


[params.links]
[[params.links.social]]
    name = "Email us"
    url = "mailto:hello@osacon.io"
    icon = "fa fa-envelope"

[[params.links.social]]
    name = "Join us!"
    url = "https://join.slack.com/t/osacommunityworkspace/shared_invite/zt-2j5oq8pa9-3z2STvxxRsrzhYkPOMwX4A"
    icon = "fab fa-slack"

[[params.links.social]]
    name = "Whatch us!"
    url = "https://www.youtube.com/@OpenSourceAnalyticsConference"
    icon = "fab fa-youtube"

[[params.links.footer_resources]] 
    name = "Team"
    url = "/team"

[[params.links.footer_resources]]
    name = "Code of Conduct"
    url = "/coc"

 [[params.links.footer_resources]]
    name = "Prospectus"
    url = "/files/OSACon2024_Prospectus_v1_4.pdf"

[[params.links.footer_resources]] 
    name = "Privacy Policy"
    url = "/privacy"


[[params.links.footer_resources]] 
    name = "Previous Speakers"
    url = "/speakers/archive"

[[params.links.footer_previous]]
    name = "OSA CON 2024"
    url = "/sessions/2024"

[[params.links.footer_previous]]
    name = "OSA CON 2023"
    url = "/sessions/2023"
[[params.links.footer_previous]]
    name = "OSA CON 2022"
    url = "https://altinity.com/osa-con2022/"
[[params.links.footer_previous]]
    name = "OSA CON 2021"
    url = "https://altinity.com/osa-con-2021/"


[permalinks]
tags = "/blog/tags/:slug/"
posts = "/:year/:month/:title/"

############################# Plugins ##############################




# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap.min.css"

[[params.plugins.css]]
link = "/plugins/bootstrap-table.min.css"

[[params.plugins.css]]
link = "/plugins/fontawesome.css"

[[params.plugins.css]]
link = "/plugins/swiper-bundle.min.css"

# JS Plugins
[[params.plugins.js]]
link="/plugins/jquery.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap-table.min.js"

[[params.plugins.js]]
link="/plugins/swiper-bundle.min.js"
